#!/bin/zsh

alias tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf'
alias help=run-help
alias glr='git pull --rebase'
alias pinit='psc-package init'
if [ "$(uname 2> /dev/null)" = "Linux" ]; then
  alias pbcopy='xsel --clipboard --input'
  alias pbpaste='xsel --clipboard --output'
fi

map()
{
  program=$1
  shift
  for arg in $@
  do
    eval $program $arg
  done
}

alias pi='map "psc-package install"'
